services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    image: laravel
    container_name: supergestao_php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - net

  db:
    image: mysql:5.7.28
    container_name: supergestao_mysql
    restart: unless-stopped
    ports:
      - "33063:3306"
    volumes:
      - ./.docker/repository/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - net

  nginx:
    image: nginx:1.19.10-alpine
    container_name: supergestao_nginx
    restart: unless-stopped
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - net

networks:
  net:
    driver: bridge
